services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    user: "$HOST_UID:$HOST_GID"
    restart: unless-stopped
    ports:
      - 8080:8080
      - 2022:2022
    volumes:
      - ${PWD}/files:/srv/sftpgo
      - ${PWD}/config:/var/lib/sftpgo