services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    restart: unless-stopped
    ports:
      - "3001"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Asia/Dhaka"
      CUSTOM_USER: "admin"
      PASSWORD: "admin"
    volumes:
      - ${PWD}/webtop_config:/config
    shm_size: "1gb"